spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/api_rest_with_spring_udemy
      username: postgres
      password: 123456
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
